package GUI;

import Code.Admin;

import javax.swing.*;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;

public class SignUpFrame {
    private JPanel mainPanel;
    private JPanel HeaderPanel;
    private JPanel FooterPanel;
    private JPanel ContentSignUpForm;
    private JTextField SignUpTxtFieldUsername;
    private JButton SignUpBtn;
    private JPasswordField SignUpPassFieldPassword;
    private JPasswordField SignUpPassFieldConfrimPassword;
    private JTextField SignUpTxtFieldName;
    private JTextField SignUpTxtFieldPhoneNo;
    private JRadioButton SignUpGenderMaleBtn;
    private JRadioButton SignUpGenderFemaleBtn;
    private JTextField SignUpTxtFieldAddress;
    private JComboBox SignUpDOBDay = new JComboBox();
    private JComboBox SignUpDOBMonth = new JComboBox();
    private JComboBox SignUpDOBYear = new JComboBox();
    private JFrame frame = new JFrame();

    public SignUpFrame() {
        $$$setupUI$$$();
        frame.setSize(900, 600);
        frame.setContentPane(this.$$$getRootComponent$$$());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);

        // Sign Up Button
        SignUpBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                boolean flag = false;
                String name = SignUpTxtFieldName.getText().toString();
                System.out.println(name);
                String userName = SignUpTxtFieldUsername.getText().toString();
                String password = SignUpPassFieldPassword.getText().toString();
                String confirmPassword = SignUpPassFieldConfrimPassword.getText().toString();
                char gender = (SignUpGenderMaleBtn.isSelected() ? 'M' : SignUpGenderFemaleBtn.isSelected() ? 'F' : null);
                String phoneNo = SignUpTxtFieldPhoneNo.getText().toString();
                String address = SignUpTxtFieldAddress.getText().toString();
                int DOBDay = Integer.parseInt(SignUpDOBDay.getSelectedItem().toString());
                int DOBMonth = Integer.parseInt(SignUpDOBMonth.getSelectedItem().toString());
                int DOBYear = Integer.parseInt(SignUpDOBYear.getSelectedItem().toString());
                Date DOB = new Date(DOBYear + 1900, DOBMonth, DOBDay);

                Admin a = new Admin(name, userName, password, gender, phoneNo, address, DOB);
                if ((SignUpTxtFieldName.getText().equals("")) || (SignUpTxtFieldUsername.getText().equals("")) || (SignUpPassFieldPassword.getText().equals("")) || (SignUpPassFieldConfrimPassword.getText().equals("")) || (SignUpTxtFieldPhoneNo.getText().equals("")) || (SignUpTxtFieldAddress.getText().equals(""))) {
                    JOptionPane.showMessageDialog(null, "Please Fill All The Fields", "Error", JOptionPane.ERROR_MESSAGE);
                } else if (!(SignUpPassFieldPassword.getText().equals(SignUpPassFieldConfrimPassword.getText()))) {
                    JOptionPane.showMessageDialog(null, "Please matching the password", "Error", JOptionPane.WARNING_MESSAGE);
                } else if (a.addAdmin()) {
                    JOptionPane.showMessageDialog(null, String.format("Admin %s Added Successfully", userName), "Admin Added", JOptionPane.INFORMATION_MESSAGE);
                    frame.dispose();
                    new LoginFrame();
                } else {
                    JOptionPane.showMessageDialog(null, String.format("Admin %s Could\'nt be Added", userName), "Erorr", JOptionPane.WARNING_MESSAGE);
                }
            }
        });
    }

    private void createUIComponents() {

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        HeaderPanel = new JPanel();
        HeaderPanel.setLayout(new GridBagLayout());
        HeaderPanel.setBackground(new Color(-11551010));
        HeaderPanel.setPreferredSize(new Dimension(366, 65));
        mainPanel.add(HeaderPanel, BorderLayout.NORTH);
        FooterPanel = new JPanel();
        FooterPanel.setLayout(new GridBagLayout());
        FooterPanel.setBackground(new Color(-11551010));
        FooterPanel.setPreferredSize(new Dimension(170, 58));
        mainPanel.add(FooterPanel, BorderLayout.SOUTH);
        final JLabel label1 = new JLabel();
        label1.setBackground(new Color(-328966));
        label1.setForeground(new Color(-328966));
        label1.setText("Vehicle Renting System");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        FooterPanel.add(label1, gbc);
        ContentSignUpForm = new JPanel();
        ContentSignUpForm.setLayout(new GridBagLayout());
        ContentSignUpForm.setBackground(new Color(-1118482));
        ContentSignUpForm.setMinimumSize(new Dimension(900, 600));
        ContentSignUpForm.setPreferredSize(new Dimension(415, 600));
        mainPanel.add(ContentSignUpForm, BorderLayout.CENTER);
        final JLabel label2 = new JLabel();
        label2.setText("UserName");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        ContentSignUpForm.add(label2, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ContentSignUpForm.add(spacer1, gbc);
        SignUpTxtFieldUsername = new JTextField();
        SignUpTxtFieldUsername.setColumns(20);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ContentSignUpForm.add(SignUpTxtFieldUsername, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        ContentSignUpForm.add(spacer2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Password");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        ContentSignUpForm.add(label3, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ContentSignUpForm.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        ContentSignUpForm.add(spacer4, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Confirm Password");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        ContentSignUpForm.add(label4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ContentSignUpForm.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        ContentSignUpForm.add(spacer6, gbc);
        SignUpBtn = new JButton();
        SignUpBtn.setBackground(new Color(-11551010));
        Font SignUpBtnFont = this.$$$getFont$$$("DejaVu Sans", Font.BOLD, 14, SignUpBtn.getFont());
        if (SignUpBtnFont != null) SignUpBtn.setFont(SignUpBtnFont);
        SignUpBtn.setForeground(new Color(-328966));
        SignUpBtn.setText("Sign Up");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 16;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ContentSignUpForm.add(SignUpBtn, gbc);
        SignUpPassFieldPassword = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ContentSignUpForm.add(SignUpPassFieldPassword, gbc);
        SignUpPassFieldConfrimPassword = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ContentSignUpForm.add(SignUpPassFieldConfrimPassword, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        ContentSignUpForm.add(label5, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ContentSignUpForm.add(spacer7, gbc);
        SignUpTxtFieldName = new JTextField();
        SignUpTxtFieldName.setColumns(20);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ContentSignUpForm.add(SignUpTxtFieldName, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        ContentSignUpForm.add(spacer8, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Gender");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        ContentSignUpForm.add(label6, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ContentSignUpForm.add(spacer9, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        ContentSignUpForm.add(spacer10, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Phone Number");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        ContentSignUpForm.add(label7, gbc);
        final JPanel spacer11 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ContentSignUpForm.add(spacer11, gbc);
        final JPanel spacer12 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.VERTICAL;
        ContentSignUpForm.add(spacer12, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Address");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 12;
        gbc.anchor = GridBagConstraints.WEST;
        ContentSignUpForm.add(label8, gbc);
        final JPanel spacer13 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ContentSignUpForm.add(spacer13, gbc);
        final JPanel spacer14 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 13;
        gbc.fill = GridBagConstraints.VERTICAL;
        ContentSignUpForm.add(spacer14, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Birth Date");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 14;
        gbc.anchor = GridBagConstraints.WEST;
        ContentSignUpForm.add(label9, gbc);
        final JPanel spacer15 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 14;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ContentSignUpForm.add(spacer15, gbc);
        final JPanel spacer16 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 15;
        gbc.fill = GridBagConstraints.VERTICAL;
        ContentSignUpForm.add(spacer16, gbc);
        SignUpGenderMaleBtn = new JRadioButton();
        SignUpGenderMaleBtn.setSelected(true);
        SignUpGenderMaleBtn.setText("Male");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        ContentSignUpForm.add(SignUpGenderMaleBtn, gbc);
        SignUpGenderFemaleBtn = new JRadioButton();
        SignUpGenderFemaleBtn.setText("Female");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 8;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.EAST;
        ContentSignUpForm.add(SignUpGenderFemaleBtn, gbc);
        SignUpTxtFieldAddress = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 12;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ContentSignUpForm.add(SignUpTxtFieldAddress, gbc);
        SignUpTxtFieldPhoneNo = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 10;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ContentSignUpForm.add(SignUpTxtFieldPhoneNo, gbc);
        SignUpDOBDay.setBackground(new Color(-1));
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("1");
        defaultComboBoxModel1.addElement("2");
        defaultComboBoxModel1.addElement("3");
        defaultComboBoxModel1.addElement("4");
        defaultComboBoxModel1.addElement("5");
        defaultComboBoxModel1.addElement("6");
        defaultComboBoxModel1.addElement("7");
        defaultComboBoxModel1.addElement("8");
        defaultComboBoxModel1.addElement("9");
        defaultComboBoxModel1.addElement("10");
        defaultComboBoxModel1.addElement("11");
        defaultComboBoxModel1.addElement("12");
        defaultComboBoxModel1.addElement("13");
        defaultComboBoxModel1.addElement("14");
        defaultComboBoxModel1.addElement("15");
        defaultComboBoxModel1.addElement("16");
        defaultComboBoxModel1.addElement("17");
        defaultComboBoxModel1.addElement("18");
        defaultComboBoxModel1.addElement("19");
        defaultComboBoxModel1.addElement("20");
        defaultComboBoxModel1.addElement("21");
        defaultComboBoxModel1.addElement("22");
        defaultComboBoxModel1.addElement("23");
        defaultComboBoxModel1.addElement("24");
        defaultComboBoxModel1.addElement("25");
        defaultComboBoxModel1.addElement("26");
        defaultComboBoxModel1.addElement("27");
        defaultComboBoxModel1.addElement("28");
        defaultComboBoxModel1.addElement("29");
        defaultComboBoxModel1.addElement("30");
        defaultComboBoxModel1.addElement("31");
        SignUpDOBDay.setModel(defaultComboBoxModel1);
        SignUpDOBDay.setPreferredSize(new Dimension(70, 28));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 14;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 20;
        ContentSignUpForm.add(SignUpDOBDay, gbc);
        SignUpDOBMonth = new JComboBox();
        SignUpDOBMonth.setBackground(new Color(-1));
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("1");
        defaultComboBoxModel2.addElement("2");
        defaultComboBoxModel2.addElement("3");
        defaultComboBoxModel2.addElement("4");
        defaultComboBoxModel2.addElement("5");
        defaultComboBoxModel2.addElement("6");
        defaultComboBoxModel2.addElement("7");
        defaultComboBoxModel2.addElement("8");
        defaultComboBoxModel2.addElement("9");
        defaultComboBoxModel2.addElement("10");
        defaultComboBoxModel2.addElement("11");
        defaultComboBoxModel2.addElement("12");
        SignUpDOBMonth.setModel(defaultComboBoxModel2);
        SignUpDOBMonth.setPreferredSize(new Dimension(70, 28));
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 14;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 24;
        ContentSignUpForm.add(SignUpDOBMonth, gbc);
        SignUpDOBYear = new JComboBox();
        SignUpDOBYear.setBackground(new Color(-1));
        final DefaultComboBoxModel defaultComboBoxModel3 = new DefaultComboBoxModel();
        defaultComboBoxModel3.addElement("1940");
        defaultComboBoxModel3.addElement("1941");
        defaultComboBoxModel3.addElement("1942");
        defaultComboBoxModel3.addElement("1943");
        defaultComboBoxModel3.addElement("1944");
        defaultComboBoxModel3.addElement("1945");
        defaultComboBoxModel3.addElement("1946");
        defaultComboBoxModel3.addElement("1947");
        defaultComboBoxModel3.addElement("1948");
        defaultComboBoxModel3.addElement("1949");
        defaultComboBoxModel3.addElement("1950");
        defaultComboBoxModel3.addElement("1951");
        defaultComboBoxModel3.addElement("1952");
        defaultComboBoxModel3.addElement("1953");
        defaultComboBoxModel3.addElement("1954");
        defaultComboBoxModel3.addElement("1955");
        defaultComboBoxModel3.addElement("1956");
        defaultComboBoxModel3.addElement("1957");
        defaultComboBoxModel3.addElement("1958");
        defaultComboBoxModel3.addElement("1959");
        defaultComboBoxModel3.addElement("1960");
        defaultComboBoxModel3.addElement("1961");
        defaultComboBoxModel3.addElement("1962");
        defaultComboBoxModel3.addElement("1963");
        defaultComboBoxModel3.addElement("1964");
        defaultComboBoxModel3.addElement("1965");
        defaultComboBoxModel3.addElement("1966");
        defaultComboBoxModel3.addElement("1967");
        defaultComboBoxModel3.addElement("1968");
        defaultComboBoxModel3.addElement("1969");
        defaultComboBoxModel3.addElement("1970");
        defaultComboBoxModel3.addElement("1971");
        defaultComboBoxModel3.addElement("1972");
        defaultComboBoxModel3.addElement("1973");
        defaultComboBoxModel3.addElement("1974");
        defaultComboBoxModel3.addElement("1975");
        defaultComboBoxModel3.addElement("1976");
        defaultComboBoxModel3.addElement("1977");
        defaultComboBoxModel3.addElement("1978");
        defaultComboBoxModel3.addElement("1979");
        defaultComboBoxModel3.addElement("1980");
        defaultComboBoxModel3.addElement("1981");
        defaultComboBoxModel3.addElement("1982");
        defaultComboBoxModel3.addElement("1983");
        defaultComboBoxModel3.addElement("1984");
        defaultComboBoxModel3.addElement("1985");
        defaultComboBoxModel3.addElement("1986");
        defaultComboBoxModel3.addElement("1987");
        defaultComboBoxModel3.addElement("1988");
        defaultComboBoxModel3.addElement("1989");
        defaultComboBoxModel3.addElement("1990");
        SignUpDOBYear.setModel(defaultComboBoxModel3);
        SignUpDOBYear.setPreferredSize(new Dimension(70, 28));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 14;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 20;
        ContentSignUpForm.add(SignUpDOBYear, gbc);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(SignUpGenderMaleBtn);
        buttonGroup.add(SignUpGenderFemaleBtn);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
